---
title: "Effective Java读书笔记"
output:
  html_notebook: default
  word_document: default
---

### 1、用静态方法代替构造方法

### 2、当构造方法参数比较多时考虑builder模式

### 3、单例模式

### 4、对于工具类，创建一个`private`的构造函数，避免被初始化

具体情形可以参考`java.util.Collections`

### 5、合理使用依赖注入



平常用的比较多的就是javabean那种方式，这种方式将类的构造分成了多步，在中间会有不一致的状态

### 7、消除过期的引用

```java
public class Stack {
    private Object[] elements;
    private int size;
    
    public Object pop() {
        if (size == 0) {
            throw new EmptyStackException();
        }
        
        return elements[--size]
    }
}
```

- 使变量拥有最小的作用域
- 当类自己管理内存时，就要提高警惕
- 常见内存泄漏场景，比如缓存、listener和callback，比如在缓存场景中可以使用`WeakedHashMap`以及使用一些内存检测工具及时发现问题

### 8、避免使用finalizer和cleaner

finalizer在java 9中已经废弃，使用cleaner代替，二者的行为都不可预测（不会可靠的运行）、危险且不必要

### 9、相对于try-finally，优先使用try-with-resources

比如

```java
public static String testTryFinally() throws IOException {
    BufferedReader br = null;
    try {
        br = new BufferedReader(new FileReader(""));
        return br.readLine();
    } finally {
        br.close();
    }
}
```

如果使用try-finally，后面的空指针错误会把前面的文件找不到错误覆盖掉，而且当打开多个资源时会造成嵌套的try-finally，代码结构显得杂乱

### 15、对类和属性给予最小的访问权限

这样可以将细节隐藏起来，实现更好的封装和模块化

四种访问权限修饰符

- `private`，只有属性所在的类可以访问
- `package-private`，只有所在包的类可以访问
- `protected`，子类和所在包的类可以访问
- `public`，所有的类都可以访问

如果一个子类重写了父类的方法，拥有的访问权限不会比父类更小，这样可以保证父类适用的地方子类也可以适用（Liskov substitution），一个极致的例子就是接口，实现接口的类方法都是`public`的

一个类的变量尽量不要`public`，不过有一个特例，就是`static final`修饰的原始类型及不可变对象，注意一个`public static final`的数组或者返回数组的方法是不安全的，下面的代码要避免，

```java
public static final Thing[] VALUES = {};
```

有两种解决方法：

```java
private static final Thing[] PRIVATE_VALUES = {};
public static final List<Thing> VALUES = Collections.unmodifiableList(Arrays.asList(PRIVATE_VALUES));
```

```java
private static final Thing[] PRIVATE_VALUES = {};

public static final Thing[] values() {
    return PRIVATE_VALUES.clone();
}
```

### 16、在`public`类中，使用方法访问，而不是`public`属性

这样就放弃了封装的好处，并且无法添加一些附加的动作，但是如果是内部类或者类只在包内访问时可以`public`属性，不过如果包内访问的地方特别多的话，这样感觉如果有变动，修改的成本也很大

### 17、最小化可变性

实现不可变类的方法：

- 不要提供修改状态的方法
- 类不可继承，可以通过加`final`关键字，更灵活的方法是使用静态工厂方法
- 所有的属性都设为`final`，事实上这条有点绝对了，只要没有方法能引起状态的改变就可以，例如对于一些不变类，里面可能会有一些非`final`的属性，来缓存一些计算量大的值
- 所有的属性都是`private`
- 对于所有的可变组建，都不要让客户代码访问到

不变类的缺点是每个不同的值都得新建一个对象，这可能造成性能问题，比如`String`类，所以在性能问题值得关注的时候，提供一个伴随类，比如`StringBuilder`和`StringBuffer`

如果不变类实现了`Serializable`接口，并且里面有一个或多个可变的属性，你必须提供一个`readObject`或`readResolve`方法，或者使用`ObjectOutputStream.writeUnshared`和`ObjectInputStream.readUnshared`方法（这条没懂，参考item88，回头再补）

除了构造方法和静态工厂方法，不要提供一个公开的初始化方法，因为这可能在多线程环境中导致一个中间状态对象的出现

### 18、组合优于继承（只是类的继承）

### 19、使用继承时要写出详细的文档，要么就别使用继承

### 20、优先使用接口而不是抽象类

### 21、设计接口为

### 22、接口的唯一作用就是定义类型

不要使用所谓的常量接口，即一个接口里仅仅包括几个常量，会导致继承这个接口的类的内部实现泄露出来，因为接口的属性都是`public`的；而且以后如果类不需要这些常量了，这些常量还会继续存在，有几种解决方式：

- 如果常量属于一个类，那就挪到这个类里
- 如果可以看做一个枚举，将它们设为枚举
- 如果你确实需要一个只有常量的对象，使用不能初始化的工具类

### 23、使用继承代替标签类

```java
class Figure {
    enum Shape {RECTANGLE, CIRCLE};
    // Tag field
    final Shape shape;
    
    double length;
    double width;
    
    double radius;
    
    Figure(double ridius) {
        shape = Shape.CIRCLE;
        this.radius = radius;
    }
    
    Figure(double length, double width) {
        shape = Shape.RECTANGLE;
        this.length = length;
        this.width = width;
    }
    
    double area() {
        switch(shape) {
            case RECTANGLE:
                return length * width;
            case CIRCLE:
                return Math.PI * (radius * radius);
            default:
                throw new AssertionError(shape);
        }
    }
}
```

这样的标签类可读性差，逻辑混乱，字段不能设为`final`的，每增加一种类型，就得增加一个`switch`分支，而且还要一些不必要的字段，可以将代码改成下面的

```java
abstract class Figure {
    abstract double area();
}

class Circle extends Figure {
    final double radius;
    
    @Override
    double area() {
        // ...
    }
}

class Rectangle extends Figure {
    double length;
    double width;
    
    @Override
    double area() {
        // ...
    }
}
```

### 24、尽量使用静态内部类

有四种内部类：

- 静态内部类
- 非静态内部类，可以获得外部类的引用，这会影响性能
- 匿名类，当且仅在非静态的上下文中拥有外部类引用，但是不能拥有静态成员，除了常量
- 局部类，和匿名类类似，出现在方法中

如果内部类不需要获得外部类的引用，那么使用静态内部类，否则使用非静态类

### 25、一个文件一个顶层类

一个java文件中只有一个顶层类，也就是你要在一个文件中包括多个`class`，只能有一个`class`在最外面，无论是不是`public`，其他的都设为内部类，否则程序运行的结果和编译器编译文件的顺序相关

### 26、尽量使用泛型

使用泛型可以在编译期间检查错误，否则只有到运行期间才会报错。

需要注意的是你可以将`List<String>`赋值给`List`，但不能赋值给`List<Object>`。如果有时候你不关心集合中的类型，比如

```java
static int numElementsInCommon(Set s1, Set s2) {
    int result = 0;
    for (Object o1 : s1) {
        if (s2.contains(o1)) {
            result++;
        }
    }
    return result;
}
```
，
它的泛型形式为`Set<?>`，前者你可以添加任何值，后者不能添加任何值，而且你不能对取出的值做任何的推断，如果这不符合需求，可以使用泛型方法和有边界的通配符

不适合泛型的场合：

- 获取类型的`class`，比如`String[].class`，`List.class`
- 使用`instanceof`判断对象的类型时，比如下面

```java
if (o instanceof Set) {
    Set<?> s = (Set<?>) o
}
```

### 27、消除`unchecked`警告

不要放过任何的`unchecked`警告，因为每个警告都以为着一个潜在的强制转型错误，当你确定类型没问题时可以使用`SuppressWarnings("unchecked")`消除警告，但是一定要把抑制警告的作用域限制到一个比较小的范围

### 28、尽量用`List`代替数组

数组和列表有两点不同，一是数组是协变的，泛型则不然，也就是你可以把`Long[]`赋值给`Object[]`，而泛型列表不然（参考item26），这样数组在运行期才发现错误，而泛型列表编译期间就可以，如果混合能混合使用它们可能会导致一些意想不到的错误，比如下面的代码

```java
// Fails at runtime
Object[] objectArray = new Long[1];
objectArray[0] = "I don't fit in"; // Throw ArrayStoreException
// Won't compile
List<Object> ol = new ArrayList<Long>();
ol.add("I don't fit in");
```

另一个不同是数组是类型必须具体化的，比如`new List<E>[], new List<String>[], new E[]`都不合法，但是注意虽然泛型创建不可以，但是转化可以，即`(T[])Object[]`是可以的。如果这些合法化的话，编译器自动产生的转化将会导致一些正确的程序出错

```java
// Generic array creation error
List<String>[] stringLists = new List<String>[1];
List<Integer> intList = List.of(42);
Object[] objects = stringLists;
object[0] = intList;
String s = stringLists[0].get(0);
```
最后一条语句取出来的是个`int`，转化为`String`就会报错，原因就是数组是协变的，所以后面四条语句都是合法的。当需要泛型的数组时，可以考虑`List`，比如下面的代码

```java
public class Chooser {
    private final Object[] choiceArray;
    
    public Chooser(Collection c) {
        choiceArray = c.toArray();
    }
    
    public Object choose() {
        return choiceArray[random];
    }
}
```

这个类每次调用`choose`方法都得使用强转，如果把`choiceArray`改成`T[]`，又会产生非受检异常，这时候可以把`choiceArray`改成一个泛型列表

### 29、尽量使用泛型

### 30、使用泛型方法

```java
public static <E> Set<E> union(Set<E> s1, Set<E> s2) {
    Set<E> result = new HashSet<>(s1);
    result.addAll(s2);
    return result;
}
```
注意泛型写在返回值的前面

递归泛型边界，类型参数被一个含有此类型的边界限制住

```java
public static <E extends Comparable<E>> E max(Collection<E> c);
```

### 31、使用带边界的通配符增加api的灵活性

假设`Stack`有这么一个方法，

```java
public void pushAll(Iterable<E> src) {
    for (E e : src) {
        push(e);
    }
}
```
这样一个`Stack<Number>`只能`pushAll(Iterable<Number>)`，但是从情理上一个`Number`的`Stack`还应该支持`Integer`, `Float`等子类型，这个时候单纯的泛型`E`就没法做了，好在泛型还有一个边界的概念，可以这样定义`pushAll`，

```java
public void pushAll(Iterable<? extends E> src) {
    for (E e : src) {
        push(e);
    }
}
```
假设还有一个`popAll`方法如下，

```java
public void popAll(Collection<E> dst) {
    while(!isEmpty()) {
        dst.add(pop());
    }
}
```

这会面临上面同样的问题，一个`Integer`的`Stack`只能使用一个`Integer`来存储，可以将`Collection<E>`改为`Collection<? super E>`来解决。

不过要注意，如果客户代码如果需要考虑通配符，那么这个api肯定是哪里出了问题。

关于通配符还有一个著名的PECS原则，即producer-extends，consumer-super，不过个人感觉不太好用，这个原则其实是由替换原则衍生出来的，替换原则说的是你可以把子类赋值给这个类的变量，一个函数的参数类也可以用子类代替。根据这个原则可以定义一个应用范围更广的`max`方法

```java
public static <E extends Comparable<? super E>> E max(Collection<? extends E> c);
```

另外就是如果泛型参数只用了一次的话可以用通配符代替，这样更简洁一些。

### 32、将泛型和可变参数一起用的时候要小心

可变参数实际上会生成一个数组来存储所有的参数，因此会面临item27类型安全的问题，但是在实际应用中，泛型的可变参数又非常有用，比如`Arrays.asList(T... a)`，因此java的设计者们做了妥协。

如何保证类型安全：

- 不修改可变参数数组
- 可变数组的引用没有溢出

Java7之前客户只要调用api就会有警告，对于Java7以后的版本可以用`SafeVarargs`注解来消除编译器的警告。注意`SafeVarargs`只能用在不能被重写的方法上，因为没法保证子类方法是安全的。

任何时候你都可以用`List`代替可变参数来消除类型安全的问题。

### 33、使用一种可以同时存储多种类型的类型安全容器

如果你想在一个容器里存储多种类型，可以使用一种*type token*的方法

```java
class Favorites {
    private Map<Class<?>, Object> favorites = new HashMap<>();
    
    public <T> void put(Class<T> type, T instance) {
        favorites.put(type, type.cast(instance));
    }
    
    public <T> get(Class<T> type) {
        return type.cast(favorites.get(type));
    }
}
```

### 83、谨慎的使用延迟初始化

### 84、不要依赖线程调度

### 85、尽量寻找序列化的替代方式

尽量不用序列化，使用json和protobuf等跨平台数据表示方式，不要从不信任的数据流中反序列化，如果非得这么做的话使用`java.io.ObjectInputFilter`

### 86、实现`Serializable`时要小心

### 87、考虑一种定制化的序列形式

### 88、编写防御性的`readObject`方法

### 89、对于实例控制，相对`readResolve`，优先使用枚举

### 90、考虑使用序列代理模式








